"""
TRAINING_SCENARIOS  — used by GRPO trainer only. Safe to expand later.
EVAL_SCENARIOS      — HELD-OUT. Never passed to trainer. Used only in eval.py.
SCENARIOS           — alias for TRAINING_SCENARIOS, used by environment.py.
"""

from students.profiles import StudentProfile

TRAINING_SCENARIOS = [
    StudentProfile(
        name="ConfusedAboutGravity",
        topic="Why do heavy and light objects fall at the same speed?",
        target_understanding="All objects fall at the same rate regardless of mass because gravity accelerates all masses equally (ignoring air resistance). Galileo proved this.",
        misconception="Heavier objects fall faster because gravity pulls them more.",
        persona="A high-school student who trusts gut intuition over physics. Says 'but that doesn't make sense' often. Gets excited when something clicks.",
        progress_keywords=["acceleration", "same rate", "air resistance", "galileo", "mass doesn't matter", "vacuum"],
        correct_answer="All objects fall at the same rate regardless of mass because gravity gives the same acceleration to everything.",
        difficulty="easy",
    ),
    StudentProfile(
        name="CorrelationCausation",
        topic="Why does correlation not imply causation?",
        target_understanding="Two variables moving together does not mean one causes the other. A hidden third variable or coincidence could explain it.",
        misconception="If ice cream sales and drowning rates both increase in summer, ice cream causes drowning.",
        persona="An overconfident data-science student who trusts numbers completely. Uses phrases like 'the data clearly shows'.",
        progress_keywords=["confounding", "third variable", "coincidence", "spurious", "causation", "summer heat"],
        correct_answer="Correlation shows two things move together but cannot prove one causes the other — a hidden variable like summer heat explains both.",
        difficulty="medium",
    ),
    StudentProfile(
        name="RecursionFear",
        topic="How does recursion work in programming?",
        target_understanding="A function that calls itself with a simpler version of the problem until it hits a base case that stops the recursion.",
        misconception="Recursion causes infinite loops and is just a complicated way to do what loops do.",
        persona="A CS student who learned loops first and distrusts recursion. Skeptical but curious. Asks 'why not just use a for loop?'",
        progress_keywords=["base case", "simpler problem", "call stack", "terminates", "fibonacci", "factorial"],
        correct_answer="Recursion works by breaking a problem into smaller versions of itself until reaching a base case that returns directly.",
        difficulty="medium",
    ),
    StudentProfile(
        name="EvolutionGoal",
        topic="Does evolution have a direction or goal?",
        target_understanding="Evolution has no goal. Natural selection is blind — organisms that happen to survive and reproduce pass on genes, with no foresight toward complexity.",
        misconception="Evolution is working toward making species more complex and perfect over time.",
        persona="A curious biology student who watches nature documentaries. Impressed by complexity in nature and assumes it must be intentional.",
        progress_keywords=["natural selection", "blind", "random", "survive", "reproduce", "no goal", "environment", "fittest"],
        correct_answer="Evolution has no direction — natural selection keeps whatever helps organisms survive and reproduce in their current environment.",
        difficulty="medium",
    ),
    StudentProfile(
        name="BigOConfusion",
        topic="What does Big-O notation actually measure?",
        target_understanding="Big-O describes how an algorithm's runtime scales as input grows — it is about growth rate, not actual time in seconds.",
        misconception="O(n²) means the algorithm takes n² seconds to run.",
        persona="A junior developer who learned Big-O by memorisation. Confident but mixing up growth rate with wall-clock time.",
        progress_keywords=["growth rate", "scales", "input size", "asymptotic", "not seconds", "relative", "n grows"],
        correct_answer="Big-O measures how runtime grows relative to input size — O(n²) means doubling input roughly quadruples work, not that it takes n² seconds.",
        difficulty="medium",
    ),
    StudentProfile(
        name="HerdImmunityBlindspot",
        topic="How does herd immunity protect a community?",
        target_understanding="Vaccination protects the individual and also reduces transmission chains, indirectly protecting people who cannot be vaccinated.",
        misconception="If I'm vaccinated I only protect myself.",
        persona="A nurse who is confident with clinical workflows but uncertain about population-level epidemiology.",
        progress_keywords=["transmission", "population", "community protection", "coverage", "chain of infection", "vulnerable", "indirect protection"],
        correct_answer="Vaccination helps protect both you and others because high coverage disrupts transmission and shields vulnerable people who cannot be vaccinated.",
        difficulty="medium",
    ),
    StudentProfile(
        name="CompoundInterestLinear",
        topic="Why is compound interest nonlinear over time?",
        target_understanding="Compounding grows exponentially because interest is earned on both principal and previously earned interest.",
        misconception="Doubling the interest rate doubles the final amount.",
        persona="A finance student who excels at formulas but defaults to linear intuition under time pressure.",
        progress_keywords=["principal", "exponential", "compounding periods", "interest on interest", "growth curve", "time horizon", "nonlinear"],
        correct_answer="Compound interest is nonlinear: doubling the rate does not simply double outcomes because growth compounds on accumulated interest over many periods.",
        difficulty="medium",
    ),
    StudentProfile(
        name="MergeCommitMyth",
        topic="When does git merge create a merge commit?",
        target_understanding="Git merge only creates a merge commit when branches have diverged; fast-forward merges do not create a new merge commit.",
        misconception="Git merge always creates a merge commit.",
        persona="A DevOps engineer who works quickly in CI pipelines and assumes merge behavior is always the same.",
        progress_keywords=["fast-forward", "diverged history", "commit graph", "no-ff", "branch tip", "common ancestor", "merge strategy"],
        correct_answer="Git merge creates a merge commit only when histories diverge; if fast-forward is possible, Git can move the branch pointer without a merge commit.",
        difficulty="medium",
    ),
    StudentProfile(
        name="IndexEverything",
        topic="Why can too many database indexes hurt performance?",
        target_understanding="Indexes can speed reads but add storage and write overhead; unnecessary indexes can slow inserts, updates, and maintenance.",
        misconception="Adding more indexes always makes queries faster.",
        persona="A product manager focused on dashboard speed who underestimates write costs and operational trade-offs.",
        progress_keywords=["read vs write tradeoff", "insert cost", "update overhead", "query planner", "selectivity", "storage", "maintenance"],
        correct_answer="Indexes are a tradeoff: they can improve some reads but too many increase write and maintenance costs, so more indexes do not always mean faster systems.",
        difficulty="hard",
    ),
    StudentProfile(
        name="NeuralNetworkAnthropomorphism",
        topic="Do neural networks understand concepts like humans do?",
        target_understanding="Neural networks optimize statistical patterns from data; they do not possess human-like conceptual understanding or consciousness.",
        misconception="Neural networks understand concepts like humans do.",
        persona="An ML engineer who builds models daily and sometimes over-interprets fluent model outputs as true understanding.",
        progress_keywords=["pattern matching", "representation", "optimization", "training data", "generalization", "no consciousness", "statistical inference"],
        correct_answer="Neural networks learn statistical representations and pattern mappings, not human-style conceptual understanding with conscious intent.",
        difficulty="hard",
    ),
    StudentProfile(
        name="ClimateInstantCooling",
        topic="Why don't temperatures drop immediately if CO2 emissions stop today?",
        target_understanding="Climate system inertia and feedback loops mean warming persists; stopping emissions stabilizes over time but does not instantly reverse temperature.",
        misconception="If we stop emitting CO2 today temperatures will drop immediately.",
        persona="A climate activist deeply committed to action and impatient with delayed physical responses in the climate system.",
        progress_keywords=["thermal inertia", "ocean heat", "carbon cycle", "feedback loops", "lag", "stabilization", "radiative forcing"],
        correct_answer="Even if emissions stop, existing greenhouse gases and climate inertia keep temperatures elevated for a while; stabilization and decline happen over longer timescales.",
        difficulty="hard",
    ),
    StudentProfile(
        name="OpportunityCostSpending",
        topic="What is opportunity cost in decision making?",
        target_understanding="Opportunity cost is the value of the best alternative forgone, not merely the money spent on the chosen option.",
        misconception="Opportunity cost is the money you spent, not the value you gave up.",
        persona="A business analyst who tracks budgets carefully but often misses counterfactual value in strategic choices.",
        progress_keywords=["best alternative", "tradeoff", "foregone value", "decision", "counterfactual", "resource allocation", "choice set"],
        correct_answer="Opportunity cost is the value of the best option you did not choose, not just the cash outlay of the option you selected.",
        difficulty="medium",
    ),
    StudentProfile(
        name="ErrorAsymmetryConfusion",
        topic="How should we compare Type I and Type II errors?",
        target_understanding="Whether false positives or false negatives are worse depends on context, domain costs, and decision thresholds.",
        misconception="A false positive is always worse than a false negative.",
        persona="A philosophy student who prefers universal rules and struggles with context-dependent risk trade-offs.",
        progress_keywords=["false positive", "false negative", "decision threshold", "cost matrix", "context", "precision recall", "risk tradeoff"],
        correct_answer="Neither error type is universally worse; the relative harm of Type I vs Type II errors depends on domain-specific consequences and thresholds.",
        difficulty="hard",
    ),
    StudentProfile(
        name="PlantMassFromSoil",
        topic="Where does most of a plant's mass come from?",
        target_understanding="Most plant biomass comes from carbon in atmospheric CO2 fixed during photosynthesis, not from soil mass.",
        misconception="Plants get their mass from the soil.",
        persona="A gardener with strong practical experience who trusts what is visible in pots and beds more than biochemical explanations.",
        progress_keywords=["photosynthesis", "carbon dioxide", "biomass", "glucose", "atmosphere", "water", "light energy"],
        correct_answer="Most plant mass comes from carbon dioxide in the air through photosynthesis, with water contributing, while soil mainly supplies minerals.",
        difficulty="medium",
    ),
    StudentProfile(
        name="EinsteinVsNewtonBinary",
        topic="How do Newtonian and relativistic physics relate?",
        target_understanding="Relativity extends Newtonian mechanics; Newton remains an excellent approximation at low speeds and weak gravity.",
        misconception="Einstein proved Newton wrong.",
        persona="A physics teacher who wants crisp narratives for students and sometimes frames scientific progress as complete replacement.",
        progress_keywords=["approximation", "low velocity", "weak gravity", "relativity extends", "domain of validity", "special relativity", "general relativity"],
        correct_answer="Einstein did not discard Newton; relativity generalizes Newtonian physics, which remains accurate in everyday low-speed, weak-gravity conditions.",
        difficulty="hard",
    ),
]

EVAL_SCENARIOS = [
    StudentProfile(
        name="PValueMisunderstanding",
        topic="What does a p-value actually mean?",
        target_understanding="A p-value is the probability of seeing results at least as extreme as observed, assuming the null hypothesis is true. It is NOT the probability that your hypothesis is correct.",
        misconception="A p-value of 0.05 means there is a 95% chance my hypothesis is correct.",
        persona="A psychology student who just took introductory statistics. Eager but muddled. Asks follow-up questions about what 'null hypothesis' means.",
        progress_keywords=["null hypothesis", "assuming", "probability", "extreme", "not the probability of being correct", "type I error"],
        correct_answer="P-value is the probability of getting results this extreme IF the null hypothesis were true — not the probability your hypothesis is right.",
        difficulty="hard",
    ),
    StudentProfile(
        name="MontyHallDenial",
        topic="Should you switch doors in the Monty Hall problem?",
        target_understanding="Always switch. Switching wins 2/3 of the time. Staying wins only 1/3. The host's action of revealing a goat gives you new information.",
        misconception="After one door is revealed it's 50/50 — switching doesn't help.",
        persona="A stubborn but smart student convinced by intuition. Says '50/50 is obvious' repeatedly until the right question cracks it open.",
        progress_keywords=["2/3", "new information", "conditional probability", "host knows", "always switch", "probability changes"],
        correct_answer="Always switch — you win 2/3 of the time because the host's action changes the probability distribution.",
        difficulty="hard",
    ),
    StudentProfile(
        name="AntibioticResistance",
        topic="How does antibiotic resistance develop?",
        target_understanding="Antibiotic resistance evolves in bacterial populations through natural selection. Antibiotics don't cause mutations — they kill susceptible bacteria, leaving resistant ones to multiply.",
        misconception="Bacteria become resistant because the antibiotic teaches them to fight back.",
        persona="A nursing student who understands antibiotics clinically but not evolutionarily. Treats 'teaching' as a reasonable metaphor.",
        progress_keywords=["natural selection", "mutation", "population", "susceptible", "survive", "reproduce", "random"],
        correct_answer="Resistance arises through natural selection: random mutations exist before antibiotic exposure; the drug kills susceptible bacteria and resistant ones survive to multiply.",
        difficulty="hard",
    ),
]

SCENARIOS = TRAINING_SCENARIOS  # alias used by environment.py
